windows:
	C:/Work/BOEM/openfast/build/bin/openfast_Win32_Debug.exe  Main_MonopileOnly_ExtPtfm_FNone_CB04.fst
# 	C:\Work\BOEM\openfast\build\bin\openfast_Win32_Debug.exe	 Main_MonopileOnly_ExtPtfm_FNone_Guyan.fst
# 	C:\Work\BOEM\openfast\build\bin\openfast_Win32_Debug.exe	 Main_MonopileOnly_ExtPtfm_FNone_CB04.fst

linux:
	/home/manu/openfast/build/glue-codes/openfast/openfast Main_MonopileOnly_ExtPtfm_FNone_CB04.fst
# 	/home/manu/openfast/build/glue-codes/openfast/openfast Main_TowerOnly.fst
# 	/home/manu/openfast/build/glue-codes/openfast/openfast Main_MonopileOnly_ExtPtfm_FNone_Guyan.fst
# 	/home/manu/openfast/build/glue-codes/openfast/openfast Main_MonopileOnly_ExtPtfm_FNone_CB04.fst
# 	/home/manu/openfast/build/glue-codes/openfast/openfast Main_MonopileOnly_ExtPtfm_FNone_CB12.fst
# 	/home/manu/openfast/build/glue-codes/openfast/openfast Main_MonopileOnly_ExtPtfm_FIndependent_CB04.fst
# 	/home/manu/openfast/build/glue-codes/openfast/openfast Main_MonopileOnly_ExtPtfm_FPushDrop_CB04.fst
# 	/home/manu/openfast/build/glue-codes/openfast/openfast Main_MonopileOnly_ExtPtfm_FPushDrop_Guyan.fst
# 	/home/manu/openfast/build/glue-codes/openfast/openfast Main_MonopileOnly.fst
